# docker-compose overrides
# overrides and extends the values in ladder99/docker-compose.yaml

# see other client repos for ideas for adding information to services.
# typically, would add 'profiles: - base' to each service used.
# that way, we know what is needed, and can start them all with
#   l99 start <setup>
# which runs the 'base' profile by default.

# version must be a string - need 3.8 for profiles
version: '3.8'

services:
  adapter:
    # note: must specify build OR image here.
    build: ./services/adapter # use ladder99/services/adapter/Dockerfile
    # see https://hub.docker.com/repository/docker/ladder99/adapter
    # image: ladder99/adapter:0.9.1-arm # for arm processors
    profiles:
      - base

  agent:
    # see https://hub.docker.com/repository/docker/ladder99/agent
    # note: default image is specified in ladder99/services/compose.yaml -
    # currently it's a cross-platform image for agent 1.7.
    # image: ladder99/agent:2.0.0.12_RC23-arm # for arm processors
    profiles:
      - base

  dozzle:
    profiles:
      - base

  grafana:
    profiles:
      - base

  # meter:
  #   profiles:
  #     - base

  portainer:
    profiles:
      - base

  postgres:
    profiles:
      - base

  pgadmin:
    profiles:
      - base

  relay:
    # note: must specify build OR image here.
    build: ./services/relay # use ladder99/services/relay/Dockerfile
    # see https://hub.docker.com/repository/docker/ladder99/relay
    # image: ladder99/relay:0.9.1-arm # for arm processors
    profiles:
      - base

# simulation:
#   profiles:
#     - base
